[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = qio
board_build.psram_type = opi   ; N16R8 使用 OPI PSRAM
board_build.arduino.memory_type = qio_opi   ; ← 关键，告诉 IDF 用 OPI PSRAM
build_flags =
    -DBOARD_HAS_PSRAM
    ;-mfix-esp32-psram-cache-issue
    ;-DSPI_FREQUENCY=40000000
    ;-D ARDUINO_USB_CDC_ON_BOOT=1
    ;-D ARDUINO_USB_MODE=1
    ; -D CONFIG_TINYUSB_HOST_ENABLED=1
    ; -D CONFIG_USB_HOST_HID_ENABLED=1
    
lib_deps =
    bodmer/TFT_eSPI
    adafruit/Adafruit GFX Library @ ^1.11.9
    ;earlephilhower/ESP8266Audio @ ^1.9.7
    esphome/ESP32-audioI2S@^2.3.0
    ;earlephilhower/ESP8266Audio @ ^1.9.7
    ;tanakamasayuki/EspUsbHost
    h2zero/NimBLE-Arduino @ ^1.4.1
    ;JPEG 解码库
    bodmer/TJpg_Decoder @ ^1.1.0
    ;
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
monitor_speed = 115200
build_src_filter = 
  +<*> 
  -<lua/src/lua.c> 
  -<lua/src/luac.c>
